/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and checked in so the read-only Docker dev
// container does not need to write to the source checkout at runtime.
